services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_SERVER=kb-sql16bi-prd\BI_PORD
      - DB_NAME=BI_DWH
      - API_KEY=test-api-key
      - SENTRY_DSN=
      - NODE_ENV=development
    env_file:
      - .env
